language: r

# right now, I only want a build to alert if I have actual failures - I know I have warnings and will fix them when I can,
# but I need to know if something changes and breaks the package.
warnings_are_errors: false

notifications:
  email:
    - ns-ffc_api_client@maskedmail.net

branches:
  except:
  - packageTest

cache: packages

r_packages:
  - testthat
  - roxygen2
  - covr

# quite a bit of this config was taken from https://stackoverflow.com/questions/55126857/resolve-rgdal-package-failing-on-travis-build
# to try to reduce the long trial and error process of which apt packages I needed for which
# R packages. Could maybe be pared down a bit to save time/resources.
addons:
  apt:
    packages:
      - gdal-bin
      - proj-bin
      - libgdal-dev
      - libgdal1-dev
      - libproj-dev
      - libgeos-dev
      - r-cran-ncdf4
      - libv8-3.14-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libudunits2-dev
      - libnetcdf-dev

repos: 
  CRAN: https://cran.rstudio.com
  rforge: http://R-Forge.R-project.org

before_install:
  - cd ffcAPIClient
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable